sudo: false
language: python
python:
- '3.6'
node_js:
- '6.0'

install:
  -  npm install --global surge

script:
  - sed "s/{{HASH}}/$TRAVIS_COMMIT/g" app/template.html > app/index.html
  - cd api && python setup.py bdist_wheel --universal && cp dist/* ../app && cd ..
  - surge -p app -d opentrons-test-deploy.surge.sh